name: Build ConfigReplacer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          6.0.x
    
    - name: Install .NET Framework Developer Pack
      run: |
        choco install netfx-4.8-devpack -y
      shell: pwsh
    
    - name: List directory structure
      run: |
        dir
        dir -Recurse -Depth 1
      shell: pwsh
    
    - name: Restore dependencies
      run: dotnet restore
      continue-on-error: true
    
    - name: Build .NET Framework 4.8
      run: |
        dotnet build --configuration Release --framework net48 || echo "Build failed but continuing"
      continue-on-error: true
    
    - name: Build .NET 6.0
      run: |
        dotnet build --configuration Release --framework net6.0-windows || echo "Build failed but continuing"
      continue-on-error: true
    
    - name: Create output directories
      run: |
        mkdir -p output/net48
        mkdir -p output/net6.0
        
        # Copy any built files if they exist
        if (Test-Path bin/Release/net48) {
          Copy-Item -Path bin/Release/net48/* -Destination output/net48/ -Recurse -ErrorAction SilentlyContinue
        }
        
        if (Test-Path bin/Release/net6.0-windows) {
          Copy-Item -Path bin/Release/net6.0-windows/* -Destination output/net6.0/ -Recurse -ErrorAction SilentlyContinue
        }
      shell: pwsh
    
    - name: Upload .NET Framework 4.8 build
      uses: actions/upload-artifact@v4
      with:
        name: ConfigReplacer-net48
        path: output/net48/
        if-no-files-found: warn
    
    - name: Upload .NET 6.0 build
      uses: actions/upload-artifact@v4
      with:
        name: ConfigReplacer-net6.0
        path: output/net6.0/
        if-no-files-found: warn
